protein = "PWNGMLMYRGRNKWPATWASICDGFEYPWDATAEDSYQWSPGNHTATDAADVTSVPYHTHWPMYELYANPPPCYASYYIVLDWKQSQHWASMIIKGTIKWDGEYPWCMGQSKDWCLPKFEIATCQSMFSQYKCFTTGWDNSWCWVARGKHIRNHSSITTGYMTGVELVVMNDHYFWQDERSWARLSAMHIYMNYTFFSRCRVPGFMPVGGVILICSKFDGDDFQCKRNQCWHMIEQFTVELHLWWRGFLRMTRVLSKKLQMVPERSPVCGYWHDVDERYGFRYFFQPSQKKIHNLKFQATCNRNFEDGKDGNTDISPWQDNFDYYCVTIQYTNKDFRPFHCGPVMDSPMQAHREHCLIRWHVDAWHHEAWRCCKMVARLMRLAEALQEQHYVDYYGTSGQWKGAQKVCMSEHFIIMQTEWDYTERIDITSSEFMVESAIMFFMYLQYQMHSFPMVMFPLKMGYQNNYQFYDGGQEGCTAFATRHMMFFDISAFPNNVDQCCRDGPMNIGKKVPTMGGCTHHWQHIADSVVLGAEWWCVVIWAMYIVMFDHFTWKPMDCPECGWGAEFGSRYLMFHHSYWLDRMNANSLFVDETDRKIKFLGQFGLKLGNGCWFPEKAESWIKRPQRGGPHSWAWEYAMTWQYYEEQWMQKELIAQMMLLHHLEAMFTFLLEIVSVHPCQKEHAEHMSTTTGNKTWGNYEFMPPVVFFKWEEKKVAFMFFCPWGNTITDNVVPVDERTHWKRDAQSTEVLSIQGFNHNHKQCNKINEFNNMCHDTAMMYCERWTCNVQVYIGHFNMIMGPVFMEAMLCIVGQHGPFPTNPLVTLDPQSGWGSTSKVIFREFSLREWTGEHNGLNFGQGRTGNHMQLVFQDKHNGMRIHAGHEIQPFSFLHDCRKHRYWMFIYQSSIWMFGAFVSSMIMYNFFPQVFLPDRNYVSCHEGLDHQIPMCEHFNW"
table = open('pesos.txt', 'r')
sum = 0
dic = {}

for line in table:
    amino = line.strip().split(" ")
    dic [amino[0]] = amino[1]

for i in protein:
    if (i in dic):
        sum += float(dic[i])

print ("{0:.3f}".format(sum))