dna = 'ACAAAGCTTCGCGATGGATCAAAGGTAAGTTAGTCGAGCTGTGTCGATAATAATTTTCCTGTTCCTTGCGCAACCACGGGCCTTCTGGGATACCCGGTCGGGTTCCGCGAGGCCACGTCCACACCCATTCGTCTCGGCGATACTTGGTATGTAGAGGGCCTTACGTGGACCGAAATGATCAGGAATTCAGGCCACCTATTACCTCTCCTGTAGCATCAAGGACCCCGTTTGCCAGTCAGCGACACAAAGTGCCATGCACGTCACACAAACCCCATAATCGGCATGTAGTGACCACAATATTCATGCAGGCGCCCCACGTCTGTTTTCACTTGCGCTAACTAGTCTCTCTCGTTCCATGCGCATGTATTCCGCATCTTAGTCCTTGCACTCAGTGCTCCTACCCAGCGGGTGATTGATTAGCTTGGTCGGCGTAGGTGTTCGTACGCCCACGGGAGCCGCTCTACTCTATTGCTCTTAAGCAGATAGCCAAGGGCATCGGCAGCTTTATAAAAAGGGGAGCTAGCTTTCTTCCATTATGTTACCTCTCGGTCTAGAGAGATCATTGGGGCCAGTTGTGAGTAGCTTGCCAGAGACGTGACATTTATGGGCTGAAGGCTCCGGAAACCGGTCTCCCGTGTACGTGTTAGTTTTCCTGTCCATTGTATCCGTTTTGGACATGGTGAGTACCATTCGGCTAGGGCCTAGTGCACAGCTCCTTCACGTACTACTTTCAGCTTGACCGAATCATTGTCACGCAGCGATGTATCTAAACGAACGGGATATCTTTGCACGGTTGCCCCGTTAATGGTCCCGTCAGTCGAGCGACGCCGAAAACGGAGACTCATGTTTATCCATAAGCTTCCA'
rdna = ''
for i in range (len(dna)):
    if dna[i] == 'A':
        rdna = 'T' + rdna
    elif dna[i] == 'G':
        rdna = 'C' + rdna
    elif dna[i] == 'C':
        rdna = 'G' + rdna
    elif dna[i] == 'T':
        rdna = 'A' + rdna

print (rdna)