dna = 'CCGCGGTCCTATCGACTTGCCTCTCGGTCCTAAGGCCGAATGTCCAAATACATATAGCTATGATTAATGCCTTCAAGAGCCTCTAGTAAAATCCCAGCTTTGTGAGGGATCAGAGGTTCCTCCGTTCGATTGCGCGCTCGAACAAGTTTCGGGTACTATAAGGTACCACGTCTTGCGCTCAGGAACGGTACAGGTTGCACATAGTTCCACTGGCTAAAATTGAGCCTGTCCTTAGTTGTTATGTTTCAGGCTCATAAGGCCGCTAGCAGCGTCACTCTCTAACTTAGGGCCTATGGTCTCGGCGCTTTAGATCGATGAAGAACCACGCATCAATTTTTAACTCACGAATAACCTACAATAGGTAGAGAACGTCTCCCTCGTTGACACTTTGACCATATCCTGGGAACGCCCAAGCAAAGTGTCGGCTCCCGTTGCATCCCGTGTTTATGCTCTGCAAACACGCCGTCTGCTGATATACAGTCACCGTGTTTTCGCAAGGTATGCCCGGCCACATGCGATAGCGTGACTAAACCCGATCTACCTGATACATATAATTTCTGATTACACGTTGAGCAATCGCGCAGACCGGTGTAATCAATAAAGAGAATGGGCCACATGGCTTAGCTGCAAACTAATAGCAGACGAGTCGGTCGTCGGACTCGAGTTGAGACCGGGATTGTCTCCTCCGTCTAGAATACTTAGCCCATGTCTATTGCACCGGACTGTGATTTTCCGGCATACTGCTCGAGATAAGTCCCCTGGAGACTCCACAATACATGGTACAGCGTATTTGCAGAGTAACAACGTAATGTCATACTATGGATCAACTCGTGTTTAATACCTGTACCGTTAACGCCTCATCCCGGACGAACGTGCGATTCATGTATGGACATCTCTAAAGTAACCATTACATCTTACCATCCTAGGGTACCC'
rna = ''
for i in range (len(dna)):
    if dna[i] == 'A':
        rna = rna + 'A'
    elif dna[i] == 'G':
        rna = rna + 'G'
    elif dna[i] == 'C':
        rna = rna + 'C'
    elif dna[i] == 'T':
        rna = rna + 'U'

print (rna)